spring:
  r2dbc:
    password: 3aYHR9izbvR6IhkR
    url: r2dbcs:mysql://rm-2ze12u572p3q4v766125010.mysql.rds.aliyuncs.com:3306/luojigou_data_panel
    username: luojigou
    name: luojigou_data_panel
    pool:
      enabled: true
    properties:
      DRIVER: mysql
      SSL: true
